//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIMWebAPI.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("webusr")]
        public string UD_USERID {
            get {
                return ((string)(this["UD_USERID"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("userws")]
        public string UD_PASSWORD {
            get {
                return ((string)(this["UD_PASSWORD"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("erp.corpservices.local")]
        public string UD_HOSTNAME {
            get {
                return ((string)(this["UD_HOSTNAME"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEV")]
        public string UD_ACCOUNT {
            get {
                return ((string)(this["UD_ACCOUNT"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNIDATA")]
        public string UD_SERVER_TYPE {
            get {
                return ((string)(this["UD_SERVER_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Native")]
        public string UD_ACCESS_MODE {
            get {
                return ((string)(this["UD_ACCESS_MODE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("udcs")]
        public string UD_RPC_SERVICE_TYPE {
            get {
                return ((string)(this["UD_RPC_SERVICE_TYPE"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("yyyyMMddHHmmssfff")]
        public string PIM_FileTimestampFormat {
            get {
                return ((string)(this["PIM_FileTimestampFormat"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("request_")]
        public string PIM_SaveFilePrefixName {
            get {
                return ((string)(this["PIM_SaveFilePrefixName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xml")]
        public string PIM_SaveFileExtensionNameXml {
            get {
                return ((string)(this["PIM_SaveFileExtensionNameXml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("oops_")]
        public string PIM_ErrorFilePrefixName {
            get {
                return ((string)(this["PIM_ErrorFilePrefixName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".err")]
        public string PIM_ErrorFileExtensionName {
            get {
                return ((string)(this["PIM_ErrorFileExtensionName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PIM_SaveFileEnabled {
            get {
                return ((bool)(this["PIM_SaveFileEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PIM_LogFileEnabled {
            get {
                return ((bool)(this["PIM_LogFileEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool PIM_ErrorFileEnabled {
            get {
                return ((bool)(this["PIM_ErrorFileEnabled"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>0</string>
  <string>1</string>
  <string>2</string>
  <string>3</string>
  <string>4</string>
  <string>5</string>
  <string>6</string>
  <string>7</string>
  <string>8</string>
  <string>9</string>
  <string>A</string>
  <string>C</string>
  <string>D</string>
  <string>M</string>
  <string>W</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection ERP_ProductItemTypeCodeList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["ERP_ProductItemTypeCodeList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int ERP_ProductCpnLength {
            get {
                return ((int)(this["ERP_ProductCpnLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".json")]
        public string PIM_SaveFileExtensionName_Json {
            get {
                return ((string)(this["PIM_SaveFileExtensionName_Json"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12")]
        public int ERP_ProductUpcLength {
            get {
                return ((int)(this["ERP_ProductUpcLength"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text/xml")]
        public string PIM_Http_MediaType_Accept {
            get {
                return ((string)(this["PIM_Http_MediaType_Accept"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Basic")]
        public string PIM_Http_AuthHeader_Schema {
            get {
                return ((string)(this["PIM_Http_AuthHeader_Schema"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Q29ycFdlYkFQSTpQSU0yMDE2")]
        public string PIM_Http_AuthHeader_Parameter {
            get {
                return ((string)(this["PIM_Http_AuthHeader_Parameter"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("restapi/integrationendpoints/InfofloNewProduct/upload?context=Context1&workspace=" +
            "Main")]
        public string PIM_Http_Restapi_Service_Uri {
            get {
                return ((string)(this["PIM_Http_Restapi_Service_Uri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("STEP-ProductInformation")]
        public string PIM_StepXml_RootElementName {
            get {
                return ((string)(this["PIM_StepXml_RootElementName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".xml")]
        public string PIM_SaveFileExtensionName_Xml {
            get {
                return ((string)(this["PIM_SaveFileExtensionName_Xml"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.6.6.31")]
        public string PIM_Http_UserHostName {
            get {
                return ((string)(this["PIM_Http_UserHostName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.1.1.1")]
        public string ERP_Http_UserHostName {
            get {
                return ((string)(this["ERP_Http_UserHostName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fiddler")]
        public string DEBUG_Http_UserAgentName {
            get {
                return ((string)(this["DEBUG_Http_UserAgentName"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PIMS9100.1|3")]
        public string UD_BASIC_PROGRAM {
            get {
                return ((string)(this["UD_BASIC_PROGRAM"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRD")]
        public string PIM_ProductIdPrefix {
            get {
                return ((string)(this["PIM_ProductIdPrefix"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\outbound\\queue")]
        public string PIM_Outbound_QueueFolderPath {
            get {
                return ((string)(this["PIM_Outbound_QueueFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\outbound\\save")]
        public string PIM_Outbound_SaveFolderPath {
            get {
                return ((string)(this["PIM_Outbound_SaveFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\outbound\\failed")]
        public string PIM_Outbound_ErrorFolderPath {
            get {
                return ((string)(this["PIM_Outbound_ErrorFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://dev.step.intranet.local/")]
        public string PIM_Http_BaseAddress_Uri {
            get {
                return ((string)(this["PIM_Http_BaseAddress_Uri"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"<?xml version=""1.0"" encoding=""utf-16""?>
<ArrayOfString xmlns:xsi=""http://www.w3.org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"">
  <string>10.130.8.72</string>
  <string>10.130.8.179</string>
  <string>10.131.34.8</string>
  <string>10.131.35.4</string>
  <string>::1</string>
  <string>localhost</string>
</ArrayOfString>")]
        public global::System.Collections.Specialized.StringCollection DEBUG_HttpUserHostNameList {
            get {
                return ((global::System.Collections.Specialized.StringCollection)(this["DEBUG_HttpUserHostNameList"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\Inbound\\queue")]
        public string PIM_Inbound_QueueFolderPath {
            get {
                return ((string)(this["PIM_Inbound_QueueFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\Inbound\\save")]
        public string PIM_Inbound_SaveFolderPath {
            get {
                return ((string)(this["PIM_Inbound_SaveFolderPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\hotfolders\\PIMWebAPI\\DEV\\data\\Inbound\\failed")]
        public string PIM_Inbound_ErrorFolderPath {
            get {
                return ((string)(this["PIM_Inbound_ErrorFolderPath"]));
            }
        }
    }
}
