//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PIMWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PIMEntities : DbContext
    {
        public PIMEntities()
            : base("name=PIMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<string> spd_AssignProductCodes(string productCodes, string sourceCode)
        {
            var productCodesParameter = productCodes != null ?
                new ObjectParameter("ProductCodes", productCodes) :
                new ObjectParameter("ProductCodes", typeof(string));
    
            var sourceCodeParameter = sourceCode != null ?
                new ObjectParameter("SourceCode", sourceCode) :
                new ObjectParameter("SourceCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spd_AssignProductCodes", productCodesParameter, sourceCodeParameter);
        }
    
        public virtual ObjectResult<string> spd_ReleaseProductCodes(string productCodes, string sourceCode)
        {
            var productCodesParameter = productCodes != null ?
                new ObjectParameter("ProductCodes", productCodes) :
                new ObjectParameter("ProductCodes", typeof(string));
    
            var sourceCodeParameter = sourceCode != null ?
                new ObjectParameter("SourceCode", sourceCode) :
                new ObjectParameter("SourceCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spd_ReleaseProductCodes", productCodesParameter, sourceCodeParameter);
        }
    
        public virtual ObjectResult<string> spd_ReserveProductCodes(Nullable<int> numberOfCodes, string optionCode, string companyGroup, string rootForCodes, Nullable<int> action, string sourceCode)
        {
            var numberOfCodesParameter = numberOfCodes.HasValue ?
                new ObjectParameter("NumberOfCodes", numberOfCodes) :
                new ObjectParameter("NumberOfCodes", typeof(int));
    
            var optionCodeParameter = optionCode != null ?
                new ObjectParameter("OptionCode", optionCode) :
                new ObjectParameter("OptionCode", typeof(string));
    
            var companyGroupParameter = companyGroup != null ?
                new ObjectParameter("CompanyGroup", companyGroup) :
                new ObjectParameter("CompanyGroup", typeof(string));
    
            var rootForCodesParameter = rootForCodes != null ?
                new ObjectParameter("RootForCodes", rootForCodes) :
                new ObjectParameter("RootForCodes", typeof(string));
    
            var actionParameter = action.HasValue ?
                new ObjectParameter("Action", action) :
                new ObjectParameter("Action", typeof(int));
    
            var sourceCodeParameter = sourceCode != null ?
                new ObjectParameter("SourceCode", sourceCode) :
                new ObjectParameter("SourceCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("spd_ReserveProductCodes", numberOfCodesParameter, optionCodeParameter, companyGroupParameter, rootForCodesParameter, actionParameter, sourceCodeParameter);
        }
    }
}
