USE [hydra_DataTransfer]
GO

/****** Object:  Table [cfg].[Sync]    Script Date: 03/03/2016 2:24:42 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [cfg].[Sync](
	[SyncID] [varchar](5) NOT NULL,
	[SyncName] [varchar](50) NULL,
	[SyncDescription] [varchar](250) NULL,
 CONSTRAINT [PK_Process] PRIMARY KEY CLUSTERED 
(
	[SyncID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


